# Generated by Django 4.1.1 on 2022-09-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('summ', models.FloatField()),
                ('description', models.TextField()),
                ('doc_num', models.CharField(max_length=30)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prime_CRM.address')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prime_CRM.client')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prime_CRM.client'),
        ),
    ]
