# Generated by Django 4.1.1 on 2022-09-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prime_CRM', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='Contrac',
        ),
    ]
