# Generated by Django 4.1.1 on 2022-09-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prime_CRM', '0002_rename_contract_contrac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contrac',
            new_name='Contract',
        ),
    ]
